# __Numpy(Numerical Python)__
* _Bilimsel hesaplamalar için kullanılır_
* _Arrayler/çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar_
* _Temelleri 1995'de (Guido Van Rossum) atılmış nihai olarak 2005 yılında(Travis Oliphant) yılında hayata geçirilmiştir_
* _Listelere benzerdir farkı;verimli veri saklama ve vektörel operasyonlardır_
* _Listelerde 3 tane int değer olsun ,listeler yapısı itibariyle her eleman aynı tipte olsa da her birisi için ayrı ayrı tip bilgisi tutar.Numpy arrayleri için kullanıcak veri tipleri arasında bir fark yoktur .İçinde tutuğu verileri fix type yani sabitlenmiş tipe zorluyor_ 
* _Arrayler ,listelerde olduğu gibi 3 int değeri için 3 tip bilgisi tutmak yerine sadece 1 tane tip bilgisi tutar bu şekilde veri saklama alanında ciddi bir avantaj sağlıyor_
* _Arrayleri diğer avantajı vektörel operasyonlardır_



##  __Klavye Kısayolları__
* _Hücre dılında:ctrl+c,x,v_
* _Hücre içinde :c,x,v_


_Kütüphaneleri daha derli toplu görmek istiyorsak :kütüphane adı cheat sheet şeklinde arat_

In [2]:
#numpy kütüphanesini içe aktar
import numpy as np

In [3]:
list_1=[1,2,3,4]
list_2=[2,3,4,5]

_Bu iki listeyi çarpmak istersek_

_Nesne yönelimli programlama ile çarpma işlemini gerçekleştirirsek_

In [4]:
ab=[]
for i in range(0,len(list_1)):
    ab.append(list_1[i]*list_2[i])
print(ab)

[2, 6, 12, 20]


_Numpy arrayleri ile vektörel çarpım yapılırsa_

In [5]:
array_1=np.array(list_1)#listenin numpy arrayine dönüştürülmesi
array_2=np.array(list_2)
print(array_1*array_2)
(array_1*array_2)

[ 2  6 12 20]


array([ 2,  6, 12, 20])

## __Numpy Array'i Oluşturmak__


In [6]:
list_3=[12,34,13,11]
array_3=np.array(list_3)
array_4=np.array([12,34,13,11])

In [7]:
print(type(array_3))
array_3

<class 'numpy.ndarray'>


array([12, 34, 13, 11])

In [8]:
np.array([3.14,4,2,13])#tüm tipler tek tipleştirldi

array([ 3.14,  4.  ,  2.  , 13.  ])

In [9]:
np.array([3,14,4,2,13],dtype="int")#tipi dışarıdan özelleştirebiliriz

array([ 3, 14,  4,  2, 13])

In [10]:
np.array([3,14,4,2,13],dtype="float32")

array([ 3., 14.,  4.,  2., 13.], dtype=float32)

__Sıfırdan array oluşturma__

In [11]:
np.zeros(5)#1 boyutlu 0 lardan oluşan ve float tipinde bir array

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5,dtype="int")#1 boyutlu 0 lardan oluşan ve int tipinde bir array

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((3,3))#3x3 tipinde 0 lardan oluşan bir matris

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((4,4),dtype="int")#1 lerden oluşan 4x4 tipinde int bir matris

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
#eğer spesifik bir değer için oluşturmak istersek
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [16]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

--------------------------------------

__BELİRLİ BİR ARTIŞ GÖSTEREN SAYILARDAN OTOMATİK ARRAY OLUŞTURMA__

In [17]:
np.arange(0,30,3)#0 dan 30 a kadar üçer üçer artan bir array oluşturuldu

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
np.linspace(0,1,10) # bu fonksiyon 0 ile 1 arasında 10 değer oluşturur(eşit aralıklı değil)-->array[5]-array[4] !=array[6]-array[5]

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.random.normal(10,4,(3,4))#ortalaması 10 olan ,standart sapması 4 olan 3x4 tipinde rassal elemanlardan oluşan bir matris oluşturulur

array([[10.35485688,  6.35727305, 13.00076184, 12.90387518],
       [ 8.07414616,  9.87700151,  7.98465599, 21.05774912],
       [ 8.20542653,  8.74725862, 14.38332535, 14.28388416]])

* tek boyutlu arrayin karşılığı -->vektördür
* iki boyutlu arrayin karşılığı-->matristir

In [20]:
np.random.randint(0,10,(3,3))#burada 0 ile 10 arasında int tipinde rastgele elemanlardan oluşan 3x3 tipinde bir array oluşturulur

array([[0, 3, 6],
       [3, 4, 6],
       [7, 9, 7]])

In [21]:
np.random.randint(0,10,(3,3))

array([[6, 6, 2],
       [2, 0, 0],
       [1, 8, 7]])

## Numpy Özellikler

* **_ndim_**: _boyut sayısı_
* **_shape_**: _boyut bilgisi_
* **_size_**: _toplam eleman sayısı_
* **_dtype_**: _array veri tipi_

In [22]:
random_array=np.random.randint(0,10,size=15)
random_array2=np.random.randint(0,10,size=(3,3))

In [23]:
random_array

array([2, 5, 4, 5, 3, 7, 2, 3, 7, 2, 3, 2, 2, 4, 5])

In [24]:
print(random_array.ndim)#1 boyutlu array
print(random_array2.ndim)#2 boyutlu array

1
2


In [25]:
print(random_array.shape)#15x1 tipinde bir array
print(random_array2.shape)#3x3 tipinde bir array

(15,)
(3, 3)


In [26]:
print(random_array.size)#arrayin tüm eleman sayısı 15 dir
print(random_array2.size)#arrayin tüm eleman sayısı 9 dur

15
9


In [27]:
print(random_array.dtype)#arrayin fix tipi int32 dir
print(random_array2.dtype)#arrayin fix tipi int32 dir

int32
int32


**_Yeniden Şekillendirme(Reshaping)_**

In [28]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.arange(1,10).reshape(3,3).ndim

2

In [31]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array_reshape=np.arange(1,10)
array_reshape

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
array_reshape.ndim

1

In [34]:
array_reshape.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
array_reshape.reshape(1,9).ndim#2 boyutlu matristir ancak tek boyut bilgisi taşır 

2

**_Birleştirme(concatenation)_**

In [36]:
array_concat1=np.arange(1,4)
array_concat2=np.arange(4,7)
array_concat3=np.arange(7,10)

In [37]:
np.concatenate([array_concat1,array_concat2])

array([1, 2, 3, 4, 5, 6])

In [38]:
np.concatenate([array_concat1,array_concat2,array_concat3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#iki boyutta concat

In [40]:
array_2D_concat=np.array([[1,2,3],
                        [3,4,5],
                        [6,7,2]])

In [41]:
np.concatenate([array_2D_concat,array_2D_concat])#satır bazlı bir birleştirme işlemi gerçekleştirildi

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 2],
       [1, 2, 3],
       [3, 4, 5],
       [6, 7, 2]])

In [42]:
np.concatenate([array_2D_concat,array_2D_concat],axis=1)#sütun bazlı bir birleştirme işlemi gerçekleştirilir

array([[1, 2, 3, 1, 2, 3],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 2, 6, 7, 2]])

**_Array Ayırma(Splitting)_**

In [43]:
array_split=np.array([1,2,3,4,5,6,7,8])

In [44]:
np.split(array_split,[3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [45]:
array_part1,array_part2,array_part3=np.split(array_split,[3,5])

In [46]:
print(array_part1)
print(array_part2)
print(array_part3)

[1 2 3]
[4 5]
[6 7 8]


In [47]:
array_split2=np.arange(16).reshape(4,4)

In [48]:
array_split2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.vsplit(array_split2,[2])#satır bazlı bölme işlemini gerçekleştirir


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [50]:
up,down=np.vsplit(array_split2,[2])
print(up)
print(down)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [51]:
np.hsplit(array_split2,[2])#sütun bazlı bölme işlemini gerçekleştirir

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [52]:
left,right=np.hsplit(array_split2,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**_Sıralama(Sorting)_**

In [53]:
array_sort=np.array([3,1,4,1,5,2,5])
np.sort(array_sort)

array([1, 1, 2, 3, 4, 5, 5])

In [54]:
array_sort

array([3, 1, 4, 1, 5, 2, 5])

In [55]:
#iki boyutlu arrayi sıralama :sıralama satır veya sütun bazlı gerçekleştirilir

In [56]:
array_sort2=np.random.normal(20,2,(3,3))
array_sort2

array([[21.48034512, 22.14895056, 19.63784242],
       [15.89452593, 19.55304677, 18.22224974],
       [19.7943917 , 23.03915286, 20.48186183]])

In [57]:
np.sort(array_sort2)#-->Satır bazlı sıralar 

array([[19.63784242, 21.48034512, 22.14895056],
       [15.89452593, 18.22224974, 19.55304677],
       [19.7943917 , 20.48186183, 23.03915286]])

In [58]:
np.sort(array_sort2,axis=0)#-->sütun bazlı sıralar

array([[15.89452593, 19.55304677, 18.22224974],
       [19.7943917 , 22.14895056, 19.63784242],
       [21.48034512, 23.03915286, 20.48186183]])

In [59]:
np.sort(array_sort2,axis=1)#-->satır bazlı sıralar

array([[19.63784242, 21.48034512, 22.14895056],
       [15.89452593, 18.22224974, 19.55304677],
       [19.7943917 , 20.48186183, 23.03915286]])

In [60]:
5*np.array([1,2,3])#deneme

array([ 5, 10, 15])

**_İndex ile elemana erişmek_**

In [61]:
array_index=np.array([[14,4,25],
                      [34,14,1],
                      [1,5,112]])
array_index

array([[ 14,   4,  25],
       [ 34,  14,   1],
       [  1,   5, 112]])

In [62]:
array_index[2,2]=10

In [63]:
array_index

array([[14,  4, 25],
       [34, 14,  1],
       [ 1,  5, 10]])

In [64]:
array_index[2,2]=9.8#tip sabitleme (fix type)

In [65]:
array_index

array([[14,  4, 25],
       [34, 14,  1],
       [ 1,  5,  9]])

**_Alt Küme İşlemleri(Slicing)_**

In [66]:
array_slice=np.arange(10,20)

In [67]:
array_slice[1:3]

array([11, 12])

In [68]:
array_slice[:3]

array([10, 11, 12])

In [69]:
array_slice[3:]

array([13, 14, 15, 16, 17, 18, 19])

In [70]:
array_slice[3::2]

array([13, 15, 17, 19])

In [71]:
array_slice[1:7:2]

array([11, 13, 15])

In [72]:
#iki boyutlu slicing

In [73]:
array_slice2=np.random.randint(10,size=(5,5))

In [74]:
array_slice2

array([[3, 6, 6, 7, 7],
       [7, 2, 0, 1, 9],
       [3, 1, 1, 7, 0],
       [9, 1, 9, 0, 4],
       [6, 6, 7, 6, 4]])

In [75]:
array_slice2[:,1]#1.sütunun tüm satırları

array([6, 2, 1, 1, 6])

In [76]:
array_slice2[0,:]#0.satırın tüm sütunları

array([3, 6, 6, 7, 7])

In [77]:
array_slice2[1:3,2:4]#2 satır ve 3.satırın sadece 3 ve 4.sütunlarını al

array([[0, 1],
       [1, 7]])

**_Alt Küme Üzerinde İşlem Yapmak_**

In [78]:
#alt arrayler üzerinde yapılan işlemler ana array üzerinde de kaydedildiğinden bu alt arrayleri bağımsılaştırmak için koyası üzerinde çalışırız

In [79]:
array_anaKume=np.random.randint(10,size=(4,4))

In [80]:
array_altKume=array_anaKume[0:3,0:2]
array_altKume

array([[6, 7],
       [6, 8],
       [8, 3]])

In [81]:
array_anaKume

array([[6, 7, 1, 7],
       [6, 8, 9, 6],
       [8, 3, 2, 3],
       [4, 3, 4, 2]])

In [82]:
array_altKume[1,1]=0
array_anaKume

array([[6, 7, 1, 7],
       [6, 0, 9, 6],
       [8, 3, 2, 3],
       [4, 3, 4, 2]])

In [83]:
array_copy_altKume=array_anaKume[0:3,0:2].copy()

In [85]:
array_copy_altKume[1,1]=1
array_anaKume

array([[6, 7, 1, 7],
       [6, 0, 9, 6],
       [8, 3, 2, 3],
       [4, 3, 4, 2]])

**_Fancy Index ile Elemanlara Erişmek_**

In [86]:
array_fancy=np.arange(0,30,3)

In [87]:
[array_fancy[1],array_fancy[3],array_fancy[5]]

[3, 9, 15]

In [88]:
fancy_index=[1,3,5]

In [92]:
array_fancy[fancy_index]
#array_fancy[1,3,5]--->IndexError veriyor

array([ 3,  9, 15])

In [93]:
#İKİ BOYUTTA FANCY 

In [96]:
array_fancy2=np.arange(9).reshape(3,3)
array_fancy2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [99]:
array_fancy2[satir,sutun]#array_fancy2[0,1] ve array_fancy2[1,2] değerlerini döndürür

array([1, 5])

In [100]:
array_fancy2[0,[1,2]]

array([1, 2])

In [101]:
#slice
array_fancy2[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

**_Koşullu Eleman İşlemleri_**

In [102]:
array_kosul=np.arange(0,10)

In [104]:
array_kosul[array_kosul<3]

array([0, 1, 2])

In [105]:
array_kosul[array_kosul>3]

array([4, 5, 6, 7, 8, 9])

In [106]:
array_kosul*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [107]:
array_kosul

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])